version: '3.8'

services:
  blockscout:
    image: newtonproject/blockscout-newton2:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        COIN: "NEW"
        CHAIN_ID: "1002"     
    restart: always
    container_name: 'blockscout-newton2'
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545/
        ETHEREUM_JSONRPC_TRACE_URL: http://host.docker.internal:8545/
        DATABASE_URL: postgresql://postgres:newton2@host.docker.internal:5432/blockscout?ssl=false
        ECTO_USE_SSL: 'false'
        SUBNETWORK: 'Newton 2.0 Devnet'
        LOGO: /images/newton_explorer_logo.svg
        LOGO_FOOTER: /images/newton_explorer_logo.svg
    ports:
      - 4000:4000

